# Generated by Django 5.0 on 2023-12-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddressbook',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
