# Generated by Django 5.0 on 2023-12-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_useraddressbook_email_useraddressbook_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddressbook',
            name='recipient',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
