# Generated by Django 4.1.13 on 2023-11-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_image_remove_productattribute_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='images',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='image',
            field=models.ImageField(null=True, upload_to='product_imgs/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
