# Generated by Django 5.0 on 2023-12-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_voucher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={'verbose_name_plural': 'Voucher'},
        ),
    ]
